#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           Servo,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Motor,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main{

int Ch1 = 1;
int Ch2 = 2;
int Ch3 = 3;
int Ch4 = 4;
	while (true) {
		motor[port5] = vexRT[Ch3]*(-1);
		motor[port6] = vexRT[Ch4];
		//arcadeControl(verticalJoystick, horizontalJoystick, threshold);
		arcadeControl(Ch2, Ch1, 4); // auto use drive Right/left motor from config
	} //wend

}
