#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftgripper,   tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           rightgripper,  tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

	task main()
		{
			while(1 == 1)
			{
		//Driving Motor Control
			if(vexRT[Ch4] == 1)
			{
 		motor[leftMotor]  = (vexRT[Ch4] + vexRT[Ch3])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch3])/2;  // (y - x)/2
 			}

 			if(vexRT[Ch3] == 1)
			{
 		motor[leftMotor]  = (vexRT[Ch4] + vexRT[Ch3])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch3])/2;  // (y - x)/2
 			}

 			else
		//Gripper Control

		if(vexRT[Btn5U] == 1)  // open corn biggest
		{
			motor[leftgripper] = 270;
			motor[rightgripper] = -270;
		}
		if(vexRT[Btn5D] == 1) // close corn
		{
			motor[leftgripper] = 0;
			motor[rightgripper] = 0;
		}
		if(vexRT[Btn8U] == 1) // open tomato
		{
			motor[leftgripper] = 80;
			motor[rightgripper] = -80;
		}
		if(vexRT[Btn8D] == 1) // close tomato
		{
			motor[leftgripper] = 30;
			motor[rightgripper] = -30;
		}



		//Arm Control
		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 40;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -40;
		}
		else
		{
			motor[armMotor] = 0;  //stop moving
		}
	}
}
