#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     Trololo,        sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*

THIS CODE IS FOR "TANK" DRIVE!!!

This code scales the input of the joysticks using an exponential equation.
Formula := (80x^3 / (127^2 * abs(x)) + (20x / abs(x))
Visit http://bit.ly/FTC3486 to find detailed instructions on the usage of this program.
Created by Jacob Mason of The Techno Warriors Advanced FTC #3486

*/


#include "JoystickDriver.c" //Joystick is included in this program

task main()
{
	bNxtLCDStatusDisplay = false;
	disableDiagnosticsDisplay();
  while(true) //infinite loop
  {

    getJoystickSettings(joystick); //retrieves data from the joystick

    if(abs(joystick.joy1_y1) > 5) //threshold of 5
    {
      long step1 = joystick.joy1_y1 * joystick.joy1_y1; // x^2
      long step2 = step1 * joystick.joy1_y1; 						// x^3
      long step3 = step2 * 80; 													// 80x^3
      float step4 = step3 / 16129; 											// 80x^3 / 127^2
      long step5 = step4 / abs(joystick.joy1_y1);				// 80x^3 / (127^2 * abs(x))
      int step6 = 20 * joystick.joy1_y1;								// 20x
      int step7 = step6 / abs(joystick.joy1_y1);				// 20x / abs(x)
      int final = step5 + step7;												// (80x^3 / (127^2 * abs(x))) + (20x / abs(x))

    	motor[Left] = final;
    }
    else
    {
      motor[Left] = 0;
    }

    if(abs(joystick.joy1_y2) > 5)
    {
      long step1 = joystick.joy1_y2 * joystick.joy1_y2;
      long step2 = step1 * joystick.joy1_y2;
      long step3 = step2 * 80;
      float step4 = step3 / 16129;
      long step5 = step4 / abs(joystick.joy1_y2);
      int step6 = 20 * joystick.joy1_y2;
      int step7 = step6 / abs(joystick.joy1_y2);
      int final = step5 + step7;

    	motor[Right] = final;
    }
    else
    {
      motor[Right] = 0;
    }
	}
}
