#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#define DEADBAND(n,d)           ((abs(n) >= (d))? (n): 0)  //Set n to zero if < d where d = deadzone value
#define JOYSTICK2MOTOR(n)       ((n)*100/128) //Normalize value to max 100
#define JOYSTICK_POWER(n)       JOYSTICK2MOTOR(DEADBAND(n, 15)) //15 is the deadband limit
#define BOUND(n,low,high)       (((n) < (low))? (low): ((n) > (high))? (high): (n))

void ArcadeDrive(int drivePower, int turnPower)
{
    //
    // Both drivePower and turnPower are in the range of -100 to 100.
    //
    motor[leftMotor] = BOUND(drivePower + turnPower, -100, 100);
    motor[rightMotor] = BOUND(drivePower - turnPower, -100, 100);
}

task main()
{
    while (true)
    {
        getJoystickSettings(joystick);
        //
        // Scale the joystick x and y to the motor power range (-100 to 100) after applying deadband.
        //
        ArcadeDrive(JOYSTICK_POWER(joystick.joy1_y1), JOYSTICK_POWER(joystick.joy1_x1));
        wait1Msec(100);
    }
}
