#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  // Standard joystick driver file from RobotC

void arcade(int x, int y)
{
	int powY;
	int powRightMotor;
	int powLeftMotor;

	powY = y;
	if (x<0) //if x negative, turning left; otherwise, turning right
	{
		powLeftMotor = (powY * (128 + (2 * x))/128);  // left motor reduced in power for right turn
		powRightMotor = powY;
	}
	else
	{
		powRightMotor = (powY * (128 - (2 * x))/128);  // right motor reduced in power for left turn
		powLeftMotor = powY;
	}
	motor[leftMotor] = powLeftMotor;
	motor[rightMotor] = powRightMotor;
}

task main()
{
	while(true){
		arcade(joystick.joy1_x1,joystick.joy1_y1);
	}
}
