#pragma config(Motor,  motorA,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

// Problem with this one is the robot creeps ie no 'deadband'

void motorControlProportional()
{
  int nMotorPower;
  int nDirection;

  nMotorPower = joystick.joy1_y1;
  nDirection  = joystick.joy1_x1;
  if (nDirection < 0)  // Turn left
  {
    motor[rightMotor] = nMotorPower; // use power settings from Y-axis
    motor[leftMotor]  = nMotorPower * (64 + nDirection) / 64;
  }
  else  // Turn right
  {
    motor[leftMotor]  = nMotorPower; // use power settings from Y-axis
    motor[rightMotor] = nMotorPower * (64 - nDirection) / 64;
  }
}

void buttonControl()  // Just a place holder for right now
{
  return;
}

task main()
{
  while (true)
  {
    getJoystickSettings(joystick);
    motorControlProportional();
    buttonControl();
  }
}
