#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  // Standard joystick driver file from RobotC
#include "ExpoEquation.c"  // Function that performs the Exponential smoothing of the joystick inputs
// Define the following macros
#define DEADBAND(n,d)           ((abs(n) >= (d))? (n): 0)  //Set n to zero if < d where d = deadzone value
#define JOYSTICK_POWER(n)       expo(DEADBAND(n,5))
#define BOUND(n,low,high)       (((n) < (low))? (low): ((n) > (high))? (high): (n)) // low=-100 and high=100

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

void ArcadeDrive(int drivePower, int turnPower) {
    motor[leftMotor] = BOUND(drivePower + turnPower, -100, 100);
    motor[rightMotor] = BOUND(drivePower - turnPower, -100, 100);
}

task drive()
{
    while (true){
        getJoystickSettings(joystick);
        // Scale the joystick x and y to the motor power range (-100 to 100) after applying deadband.
        ArcadeDrive(JOYSTICK_POWER(joystick.joy1_y1), JOYSTICK_POWER(joystick.joy1_x1));
        wait1Msec(100);
    }
}

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of TeleOp phase.

  StartTask(drive);  // give driver control of the wheels.  Using separate task so driver never loses control of bot.
  while (true)
  {}
}
