#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     hook1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     hook2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    cube,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

void initializeRobot() {
  return;
}
task lowerHang() {
	// LOWER HOOK
	///*
	motor[hook1] = -75;
	wait10Msec(230);
	motor[hook1] = 0;
	//*/
}
task main()
{
  initializeRobot();
	waitForStart();

	// RAISE HOOK
	///*
	motor[hook1] = 75;
	wait10Msec(230);
	motor[hook1] = 0;
	//*/

	// DRIVE TO PENDULUM
	///*
	motor[rightWheel] = 75;
	motor[leftWheel] = 75;
	wait10Msec(70);
	motor[rightWheel] = 0;
	motor[leftWheel] = 0;
	wait10Msec(50);
	//*/

	// DROP CUBE
	///*
	servo[cube] = 220;
	wait1Msec(400);
	//*/

	// BACK UP
	///*
	motor[rightWheel] = -75;
	motor[leftWheel] = -75;
	wait10Msec(80);
	motor[rightWheel] = 0;
	motor[leftWheel] = 0;
	wait10Msec(50);
	//*/

	StartTask(lowerHang);

	// DRIVE TO RAMP
	motor[rightWheel] = 75;
	motor[leftWheel] = -75;
	wait10Msec(40);
	motor[rightWheel] = 75;
	motor[leftWheel] = 75;
	wait10Msec(95);
	motor[rightWheel] = 0;
	motor[leftWheel] = 0;
	wait10Msec(20);
	motor[rightWheel] = -75;
	motor[leftWheel] = 50;
	wait10Msec(140);
	motor[rightWheel] = -75;
	motor[leftWheel] = -75;
	wait10Msec(20);
	motor[rightWheel] = 100;
	motor[leftWheel] = 100;
	wait10Msec(220);

	// STOP
	motor[rightWheel] = 0;
	motor[leftWheel] = 0;
	wait10Msec(100);

}
