#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rightWheel,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftWheel,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     hook1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     hook2,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    cube,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#define DEADBAND_ZONE 10

void initializeRobot() {
	servo[cube] = 0;
  return;
}

task main() {
  initializeRobot();

  waitForStart();   // wait for start of tele-op phase
	while(true) {
	 getJoystickSettings(joystick);
	 bool hook;

	 //
	 // Drive
	 //
	 int turn = joystick.joy1_x1;
	 int power = joystick.joy1_y1;
   motor[leftWheel] = power + turn;
   motor[rightWheel] = power - turn;

   //
   // Hook
   //
   if(joy2Btn(7) == 1) {hook = true; motor[hook1] = 0; motor[hook2] = 0;}
   if(joy2Btn(8) == 1) {hook = false; motor[hook1] = 0; motor[hook2] = 0;}
	 if(hook == true) {
   		if(joystick.joy2_TopHat == 0) {
   				motor[hook1] = 50;
   		} else if(joystick.joy2_TopHat == 4) {
   				motor[hook1] = -50;
   		} else motor[hook1] = 0;
   } else {
   		if(joystick.joy2_TopHat == 0) {
   			motor[hook2] = 50;
   		}
   		else if(joystick.joy2_TopHat == 4) {
   			motor[hook2] = -50;
   		} else motor[hook2] = 0;
   }

   //
   // Flag Raiser
   //
	 if(abs(joystick.joy2_y2) < DEADBAND_ZONE) {
	    motor[flag] = 0;
	 } else {
   		motor[flag] = joystick.joy2_y2;
   }

   //
   // Arm
   //
   if(abs(joystick.joy2_y1) < DEADBAND_ZONE) {
	    motor[arm] = 0;
	 } else {
   		motor[arm] = joystick.joy2_y1 * .3;
   }
   if(joy2Btn(5) == 1) {
       servo[gripper] = 185;
   }
	 if(joy2Btn(6) == 1) {
	   	 servo[gripper] = 135;
	 }
	}
}
